apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kustom-webapp
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./kustom-webapp/overlays/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default 